create database db_users; 
use db_users; 

CREATE TABLE `t_users` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `username` varchar(255) default NULL,
  `surname` varchar(255) default NULL,
  `password` varchar(255),
  `country` varchar(100) default NULL,
  `email` varchar(255) default NULL,
  `role` varchar(255) default NULL,
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

INSERT INTO `t_users` (`username`,`surname`,`password`,`country`,`email`,`role`) VALUES ("Vincent","Andrews","5365","Switzerland","orci.Phasellus.dapibus@a.org","User"),("Odysseus","Gould","5127","Belgium","Fusce.aliquet@mus.edu","User"),("Hop","Beasley","2088","British Indian Ocean Territory","vitae@egestasAliquamfringilla.org","Admin"),("Laith","Hahn","4545","Costa Rica","mauris.elit@CuraeDonec.com","Admin"),("Brandon","Winters","4665","Antigua and Barbuda","sit.amet@lobortis.net","User");
INSERT INTO `t_users` (`username`,`surname`,`password`,`country`,`email`,`role`) VALUES ("Upton","Santiago","9696","New Zealand","in@arcu.com","Admin"),("Julian","Holden","4817","Mayotte","Donec@ipsumnonarcu.org","User"),("Dustin","Mcdonald","1618","Cameroon","ut.dolor@SuspendisseduiFusce.com","User"),("Lyle","Carlson","2630","Nigeria","interdum.ligula.eu@laciniavitae.com","Admin"),("Salvador","Bryan","4438","Iran","interdum.Nunc@dolor.com","Admin");
INSERT INTO `t_users` (`username`,`surname`,`password`,`country`,`email`,`role`) VALUES ("Sean","Phillips","1666","France","viverra@pedenonummyut.com","User"),("Castor","Kemp","3995","Iran","dui.in@Morbinon.net","User"),("Luke","Williams","6296","Iceland","sem@Aliquamornare.ca","Admin"),("Ezra","Kaufman","9945","Cameroon","interdum@adlitora.ca","Admin"),("Bruce","Carroll","5225","Venezuela","mauris@Nullasempertellus.com","Admin");
INSERT INTO `t_users` (`username`,`surname`,`password`,`country`,`email`,`role`) VALUES ("Preston","Holt","5540","Antarctica","tristique@auctorullamcorpernisl.ca","User"),("Felix","Cotton","9689","South Georgia and The South Sandwich Islands","et.magna@Nullam.edu","User"),("Aquila","Frost","7424","Papua New Guinea","ac.feugiat@inmolestie.co.uk","User"),("Beau","Cherry","9847","Cocos (Keeling) Islands","mollis.Duis@loremvitaeodio.ca","User"),("Randall","Carver","6878","Cayman Islands","massa.non.ante@Aenean.net","User");
INSERT INTO `t_users` (`username`,`surname`,`password`,`country`,`email`,`role`) VALUES ("Merrill","Marsh","4591","Estonia","ligula@mus.edu","User"),("Oleg","Maynard","7921","Bolivia","at.auctor@ipsum.edu","User"),("Louis","Hunter","8292","Sweden","Aliquam.nec@fermentumarcuVestibulum.co.uk","User"),("Leo","Douglas","7921","China","consequat.enim@Nunc.com","Admin"),("Paki","Mcconnell","2135","Bulgaria","arcu.vel@malesuadafames.com","Admin");
INSERT INTO `t_users` (`username`,`surname`,`password`,`country`,`email`,`role`) VALUES ("Forrest","Patel","6145","Georgia","parturient.montes.nascetur@eteros.net","Admin"),("Cain","Bass","5717","Sao Tome and Principe","imperdiet@pedeCumsociis.ca","User"),("Nehru","Matthews","9337","South Sudan","cursus@ametmetus.co.uk","User"),("Jameson","Davidson","6399","Albania","magna.Phasellus@eleifendCrassed.org","User"),("William","Ramsey","3727","Andorra","Sed.eu.nibh@maurisSuspendisse.org","Admin");
INSERT INTO `t_users` (`username`,`surname`,`password`,`country`,`email`,`role`) VALUES ("Ashton","Le","6145","Zimbabwe","Donec.elementum@luctusfelis.net","User"),("Tucker","David","3506","Cook Islands","mauris.id.sapien@faucibuslectus.com","User"),("Brent","Sweeney","4402","Mauritania","purus.in@tempor.edu","User"),("Theodore","Combs","3760","South Sudan","at.sem.molestie@libero.org","User"),("Edan","Camacho","2049","Palestine, State of","molestie@etmagnisdis.edu","User");
INSERT INTO `t_users` (`username`,`surname`,`password`,`country`,`email`,`role`) VALUES ("Cyrus","Hopper","3255","Turks and Caicos Islands","Morbi@massa.org","User"),("Jermaine","Ingram","7359","Grenada","lectus.sit.amet@infelisNulla.org","Admin"),("Harding","Lindsey","9346","Palestine, State of","Sed.congue@idmollisnec.net","User"),("Thane","Rios","6219","Tajikistan","id.magna@pedeac.net","User"),("Alfonso","Thompson","7552","Kyrgyzstan","molestie@aliquetmagnaa.net","Admin");
INSERT INTO `t_users` (`username`,`surname`,`password`,`country`,`email`,`role`) VALUES ("Drake","Osborn","3334","Ethiopia","ac.turpis@erosProinultrices.co.uk","Admin"),("Amal","Evans","1763","Virgin Islands, United States","ligula.elit@Craseutellus.net","Admin"),("Harding","Campos","5373","Cuba","Vivamus.non.lorem@dignissimpharetraNam.org","User"),("Bert","Kelley","3710","Uzbekistan","dolor@aliquetlobortisnisi.net","Admin"),("Brandon","Reyes","5789","Nepal","gravida.mauris.ut@sit.org","User");
INSERT INTO `t_users` (`username`,`surname`,`password`,`country`,`email`,`role`) VALUES ("Yardley","Tucker","3033","Saudi Arabia","ipsum.cursus.vestibulum@tellusloremeu.ca","Admin"),("Maxwell","Copeland","6310","Ukraine","Duis.mi.enim@necurnaet.net","Admin"),("Daniel","Gilbert","6239","Senegal","pede.nec@idmollis.ca","User"),("Hashim","Frederick","3910","Vanuatu","tellus.lorem@dignissimlacusAliquam.co.uk","Admin"),("Wallace","Walter","9235","Cocos (Keeling) Islands","Lorem@Proinnislsem.edu","User");
INSERT INTO `t_users` (`username`,`surname`,`password`,`country`,`email`,`role`) VALUES ("Cain","Bryan","4030","Lesotho","Cras.vulputate.velit@fermentummetusAenean.ca","Admin"),("Sebastian","Price","8298","Yemen","Nullam@erosturpis.net","User"),("Lars","Benton","2144","Kiribati","in.sodales.elit@sit.co.uk","Admin"),("Jin","Mcconnell","5008","Puerto Rico","Morbi@Proinultrices.co.uk","Admin"),("Justin","Simmons","5875","Antigua and Barbuda","vitae@natoquepenatibuset.edu","User");
INSERT INTO `t_users` (`username`,`surname`,`password`,`country`,`email`,`role`) VALUES ("Drake","Alexander","9585","Jordan","sociis.natoque@Duisacarcu.ca","User"),("Clinton","Marsh","6275","Senegal","sit.amet@pharetrautpharetra.net","Admin"),("Berk","Shepherd","5078","Holy See (Vatican City State)","ipsum.Phasellus.vitae@urnaNunc.org","User"),("Gil","Blake","4235","Angola","sit@Fusce.ca","Admin"),("Oscar","Kelly","5979","Turks and Caicos Islands","risus.odio.auctor@sed.co.uk","User");
INSERT INTO `t_users` (`username`,`surname`,`password`,`country`,`email`,`role`) VALUES ("Lance","Newton","6037","Dominican Republic","Vivamus@egestashendrerit.ca","User"),("Zachery","Gillespie","7752","Netherlands","lorem.Donec@lacusvestibulumlorem.edu","User"),("Jonah","Payne","2876","Mongolia","Nulla@CurabiturmassaVestibulum.co.uk","User"),("Ralph","Barnes","8582","Georgia","Vivamus@eget.ca","Admin"),("Phelan","Chapman","8043","Chile","Curabitur.sed@sodales.net","User");
INSERT INTO `t_users` (`username`,`surname`,`password`,`country`,`email`,`role`) VALUES ("Basil","Stuart","7814","Georgia","facilisis.lorem.tristique@lectusconvallisest.com","Admin"),("Acton","Olson","6212","American Samoa","placerat@nullamagnamalesuada.edu","Admin"),("Alvin","Hobbs","4805","Afghanistan","scelerisque.lorem@ipsumporta.net","Admin"),("Vincent","Holland","2850","Turkmenistan","blandit.mattis@sedhendrerit.co.uk","Admin"),("Rajah","Greer","6237","Afghanistan","Lorem.ipsum@molestiepharetranibh.com","User");
INSERT INTO `t_users` (`username`,`surname`,`password`,`country`,`email`,`role`) VALUES ("Rudyard","Diaz","8263","Palestine, State of","Phasellus.in@arcu.edu","User"),("Amal","Black","6953","Romania","Donec@eleifend.co.uk","Admin"),("Ryan","Dalton","2063","Mozambique","dignissim.magna@risus.edu","Admin"),("Jack","William","8120","Iran","et@aarcu.co.uk","User"),("Vance","Baker","5646","Haiti","sit.amet.dapibus@ullamcorper.edu","User");
INSERT INTO `t_users` (`username`,`surname`,`password`,`country`,`email`,`role`) VALUES ("Armando","Mcgowan","8063","Maldives","nibh.Quisque.nonummy@scelerisquesedsapien.net","Admin"),("Drew","Wilcox","8970","Guinea","neque@enim.ca","User"),("Martin","Mcintosh","8587","Botswana","nulla@Duisami.edu","User"),("Beau","Willis","7619","Angola","in.lobortis@mattisInteger.co.uk","User"),("Igor","Everett","4237","Congo, the Democratic Republic of the","ridiculus.mus@parturientmontesnascetur.edu","Admin");
INSERT INTO `t_users` (`username`,`surname`,`password`,`country`,`email`,`role`) VALUES ("Branden","Marshall","7177","Togo","Suspendisse.ac@aliquet.co.uk","User"),("Sawyer","Deleon","2131","Panama","erat.vel@necluctus.ca","User"),("Silas","Williams","2318","Iran","tempor.arcu@ipsumDonecsollicitudin.org","User"),("Raphael","Deleon","7219","Lebanon","ipsum.primis@rhoncusDonecest.ca","Admin"),("Callum","Burks","8624","Hong Kong","scelerisque.dui.Suspendisse@vellectusCum.net","User");
INSERT INTO `t_users` (`username`,`surname`,`password`,`country`,`email`,`role`) VALUES ("Hu","Rush","1219","Marshall Islands","sed@aliquam.com","User"),("Byron","Golden","7375","Nicaragua","amet.massa@ultricesposuerecubilia.co.uk","User"),("Xenos","Dejesus","8724","Mexico","euismod.et@etmagnaPraesent.net","User"),("Talon","Hawkins","6605","Guadeloupe","mauris.Integer.sem@Pellentesquetincidunt.ca","Admin"),("Austin","Cotton","1149","Oman","libero@in.ca","Admin");
INSERT INTO `t_users` (`username`,`surname`,`password`,`country`,`email`,`role`) VALUES ("Tarik","Wheeler","3233","Sierra Leone","justo.faucibus@felis.net","User"),("Hayes","Coffey","7290","Iran","cursus.Integer.mollis@Fusce.com","User"),("Caldwell","Hancock","5469","Nepal","neque@ettristique.co.uk","Admin"),("Wade","Valentine","6608","Senegal","mollis.dui.in@orcilobortisaugue.com","User"),("Gray","Calderon","9898","Saint Pierre and Miquelon","arcu@sagittis.net","Admin");
INSERT INTO `t_users` (`username`,`surname`,`password`,`country`,`email`,`role`) VALUES ("Dean","Horn","6484","Iraq","ante.blandit@turpisNulla.com","Admin"),("Henry","Pitts","7970","Curaçao","auctor@eratnonummyultricies.edu","User"),("Hayden","Delacruz","6011","Monaco","id.libero.Donec@rutrumnon.net","User"),("Rudyard","Hawkins","7096","Bahrain","nunc@Donecnibh.edu","Admin"),("Amal","Weeks","9028","Uganda","cursus.diam@felispurusac.edu","Admin");

INSERT INTO `t_users` (`username`,`surname`,`password`,`country`,`email`,`role`) VALUES ("Admin","Sudo","pass","Mexico","Admin@gmail.com","Admin"); 